-- MotherDuck / DuckDB schema for tracking athlete programming and feedback
-- Compatible with the CSV outputs generated by the `programming-audit-council` skill
-- Usage: run in MotherDuck SQL editor or local DuckDB CLI (duckdb mydb.duckdb < schema.sql)

CREATE TABLE IF NOT EXISTS athletes (
    athlete_id      VARCHAR PRIMARY KEY,
    display_name    VARCHAR,           -- use initials or codename, never full legal name in shared DBs
    profile         VARCHAR,           -- powerlifter | weightlifter | football_rb | hybrid_hyrox | general_population
    sport_role      VARCHAR,           -- e.g. RB, snatch specialist, 93kg class
    onboarding_date DATE,
    notes           VARCHAR
);

CREATE TABLE IF NOT EXISTS weekly_programs (
    program_id      VARCHAR PRIMARY KEY,
    athlete_id      VARCHAR REFERENCES athletes(athlete_id),
    week_number     INTEGER,
    phase           VARCHAR,           -- accumulation | intensification | realization | peaking | taper | in_season | off_season
    version         VARCHAR,           -- v1 | v2
    focus           VARCHAR,           -- e.g. LowerPower_Posterior
    created_at      TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS exercises_log (
    log_id          VARCHAR PRIMARY KEY,
    program_id      VARCHAR REFERENCES weekly_programs(program_id),
    day_number      INTEGER,
    exe_code        VARCHAR,           -- EXE column from programming CSV
    exercise_name   VARCHAR,
    sets            INTEGER,
    reps            VARCHAR,           -- can be a range or "AMRAP"
    intensity       VARCHAR,           -- % or RPE
    velocity_target DOUBLE,            -- m/s, nullable
    tempo           VARCHAR,
    rest_seconds    INTEGER,
    notes           VARCHAR,
    -- actuals, filled post-session
    actual_reps     VARCHAR,
    actual_rpe      DOUBLE,
    actual_velocity DOUBLE
);

CREATE TABLE IF NOT EXISTS feedback_sheet (
    feedback_id     VARCHAR PRIMARY KEY,
    athlete_id      VARCHAR REFERENCES athletes(athlete_id),
    week_number     INTEGER,
    log_date        DATE,
    bodyweight_am   DOUBLE,
    sleep_hours     DOUBLE,
    fatigue_pre     INTEGER,           -- 0-10 scale
    soreness        INTEGER,           -- 0-10 scale
    pain_check      INTEGER,           -- 0-10 scale, triggers Sanford Gate if >=3
    field_readiness INTEGER,           -- 0-10 scale
    main_lift_load  VARCHAR,           -- free text summary of key loads
    coach_notes     VARCHAR
);

-- Example view: flag weeks requiring Sanford Gate review
CREATE VIEW IF NOT EXISTS sanford_flags AS
SELECT athlete_id, week_number, log_date, pain_check, coach_notes
FROM feedback_sheet
WHERE pain_check >= 3;

-- Example view: weekly progression readiness check (per programming-audit-council rules)
CREATE VIEW IF NOT EXISTS progression_readiness AS
SELECT
    f.athlete_id,
    f.week_number,
    AVG(f.sleep_hours) AS avg_sleep,
    MAX(f.pain_check) AS max_pain,
    CASE
        WHEN AVG(f.sleep_hours) >= 7 AND MAX(f.pain_check) < 3 THEN 'ADVANCE_ELIGIBLE'
        ELSE 'HOLD_OR_SCALE'
    END AS progression_flag
FROM feedback_sheet f
GROUP BY f.athlete_id, f.week_number;
